"""CriticAgent for visual consistency and quality assurance."""

from typing import List, Optional
import google.genai as genai
from google.genai import types
from pydantic import BaseModel
from app.core.config import settings

class ConsistencyReport(BaseModel):
    """Report generated by The Critic after comparing assets."""
    is_consistent: bool
    score: float  # 0.0 to 1.0
    issues: List[str]
    recommendations: Optional[str] = None

class CriticAgent:
    """The 'Critic' agent responsible for maintaining visual and brand identity."""

    def __init__(self, model_name: str = "gemini-2.0-flash"):
        """Initializes The Critic.

        Args:
            model_name: The name of the Gemini model to use for vision tasks.
        """
        self.client = genai.Client(
            vertexai=True,
            project=settings.PROJECT_ID,
            location=settings.LOCATION
        )
        self.model_name = model_name

    def verify_consistency(
        self,
        reference_image_bytes: bytes,
        target_image_bytes: bytes,
        criteria: str = "visual identity, colors, and character features"
    ) -> ConsistencyReport:
        """Compares a target image against a reference image for consistency.

        Args:
            reference_image_bytes: The original 'Signature Asset' image.
            target_image_bytes: The newly generated image to verify.
            criteria: Specific aspects to focus on during verification.

        Returns:
            ConsistencyReport: Detailed analysis of the consistency.
        """
        
        prompt = f"""
        Analyze the two provided images for visual consistency based on the following criteria: {criteria}.
        
        Image 1 is the reference (Signature Asset).
        Image 2 is the generated content.
        
        Output your analysis in JSON format with the following keys:
        - is_consistent (boolean)
        - score (float between 0 and 1)
        - issues (list of strings)
        - recommendations (string or null)
        """

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=[
                types.Content(
                    role="user",
                    parts=[
                        types.Part.from_bytes(data=reference_image_bytes, mime_type="image/jpeg"),
                        types.Part.from_bytes(data=target_image_bytes, mime_type="image/jpeg"),
                        types.Part.from_text(text=prompt)
                    ]
                )
            ],
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=ConsistencyReport
            )
        )

        # Parse the structured response
        return response.parsed
