"""GenesisAgent for conceptualizing new Muses and drafting their DNA."""

import uuid
import google.genai as genai
from google.genai import types
from app.core.config import settings
from app.core.schemas.genesis import GenesisDNA, MuseProposal

class GenesisAgent:
    """Agent responsible for the 'Inspiration' phase of Muse creation.
    
    This agent uses high-level reasoning to generate unique, coherent 
    personalities and visual anchors for new digital entities.
    """

    def __init__(self, model_name: str = "gemini-3.0-pro"):
        self.client = genai.Client(
            vertexai=True,
            project=settings.PROJECT_ID,
            location=settings.LOCATION
        )
        self.model_name = model_name

    def generate_random_concept(self) -> MuseProposal:
        """Generates a complete Muse concept for the 'Surprise Me' mode."""
        
        prompt = """
        You are the 'Genesis Architect'. Your goal is to create a unique, 
        high-potential digital influencer concept.
        
        TASK:
        1. Conceptualize a Muse with a specific niche, personality, and visual style.
        2. Draft their full DNA including a 'Moral Graph' and 'Visual Constancy' anchors.
        3. Create a 'preview_prompt' that would generate their canonical master portrait.
        
        Return a JSON object following the MuseProposal schema.
        Ensure the concept is avant-garde, autonomous, and digitally native.
        """

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=[
                types.Content(
                    role="user",
                    parts=[types.Part.from_text(text=prompt)]
                )
            ],
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=MuseProposal
            )
        )

        proposal = response.parsed
        # Ensure a unique ID if not generated by LLM
        if not proposal.proposal_id:
            proposal.proposal_id = str(uuid.uuid4())[:8]
            
        return proposal

    def refine_dna_from_prompt(self, user_prompt: str) -> MuseProposal:
        """Generates a concept based on a specific user 'Imagine' prompt."""
        
        prompt = f"""
        Transform this raw idea into a structured Muse identity:
        "{user_prompt}"
        
        TASK:
        1. Expand the user's idea into a coherent persona.
        2. Draft the full GenesisDNA.
        3. Refine the user's prompt into a 'preview_prompt' optimized for high-end portrait rendering.
        
        Return a JSON object following the MuseProposal schema.
        """

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=[
                types.Content(
                    role="user",
                    parts=[types.Part.from_text(text=prompt)]
                )
            ],
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=MuseProposal
            )
        )

        return response.parsed
